version: '3.8'

services:
  frontend:
    build:
      context: ./Hotelfrontend/bhushan-hotel
      dockerfile: Dockerfile
    image: 8084577018/hotelbooking-frontend
    ports:
      - "5173:5173"
    depends_on:
      - app
  
  app:
    build:
      context: ./Hotelbackend/HotelBooking
      dockerfile: Dockerfile
    image: 8084577018/myapp:latest 
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hoteldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Cb@64565120
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: hoteldb
      MYSQL_ROOT_PASSWORD: Cb@64565120
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
