name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: |
          cd Hotelfrontend/bhushan-hotel
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest