name: Deploy to AWS ECS

on:
  push:
    branches: ["main"]
      
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2



    - name: Build and push Docker image
      id: build-image
      run: |
         docker-compose up --build
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         docker compose push

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_ACCESS_KEY_ID }}
        username: ubuntu
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          source: "./docker-compose.yml"
          target: ./docker-compose.yml

    - name: Docker pull and run on hub 
      uses: appleboy/ssh-action@master
      with:
          host: ${{secrets.AWS_ACCESS_KEY_ID}}
          username: ubuntu
          key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          script: 
           sudo docker-compose down
           sudo docker-compose pull
           sudo docker-compose up

